# Generated by Django 5.0.6 on 2025-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='media_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
